
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 5;
  public static final int PUNTO_COMA = 7;
  public static final int EOF = 0;
  public static final int NUMERO = 2;
  public static final int LLAVES_FIN = 4;
  public static final int error = 1;
  public static final int HEX = 8;
  public static final int DOS_PUNTOS = 6;
  public static final int LLAVES_INICIO = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "LLAVES_INICIO",
  "LLAVES_FIN",
  "COMA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "HEX"
  };
}
